// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCh1MeRshDCuSwJ1Wnb5PFcM6Rm_h7h5I',
    appId: '1:840950673551:web:a7bd117f029a5207be00fa',
    messagingSenderId: '840950673551',
    projectId: 'spiritsyestem',
    authDomain: 'spiritsyestem.firebaseapp.com',
    storageBucket: 'spiritsyestem.firebasestorage.app',
    measurementId: 'G-FZMMQ0RVD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJJXTWkBmQhZsQH5aOYRfUwGzPtmq9Iu0',
    appId: '1:840950673551:android:2c4473b97834056cbe00fa',
    messagingSenderId: '840950673551',
    projectId: 'spiritsyestem',
    storageBucket: 'spiritsyestem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdjs-5gxX29Dm95c5NrAHZ5vRKYJpYVPE',
    appId: '1:840950673551:ios:297ac2f1040b01b6be00fa',
    messagingSenderId: '840950673551',
    projectId: 'spiritsyestem',
    storageBucket: 'spiritsyestem.firebasestorage.app',
    iosBundleId: 'com.example.lingolens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdjs-5gxX29Dm95c5NrAHZ5vRKYJpYVPE',
    appId: '1:840950673551:ios:297ac2f1040b01b6be00fa',
    messagingSenderId: '840950673551',
    projectId: 'spiritsyestem',
    storageBucket: 'spiritsyestem.firebasestorage.app',
    iosBundleId: 'com.example.lingolens',
  );
}
