import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:lingolens/core/di/injection_container.dart';
import 'package:lingolens/core/theme/app_theme.dart';
import 'package:lingolens/features/vocabulary/presentation/bloc/vocabulary_bloc.dart';
import 'package:lingolens/features/vocabulary/presentation/pages/vocabulary_page.dart';

// Generated by FlutterFire CLI – replace with your actual config
import 'firebase_options.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  await initDependencies();
  runApp(const LingoLens());
}

class LingoLens extends StatelessWidget {
  const LingoLens({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'LingoLens',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.dark,
      home: BlocProvider(
        create: (_) => sl<VocabularyBloc>()..add(const LoadWordsEvent()),
        child: const VocabularyPage(),
      ),
    );
  }
}
